# This is a deployment configuration file.
apiVersion: apps/v1  # The apiVersion for Deployment resource
kind: Deployment  # The kind of the resource, in this case a Deployment
metadata:
  name: echo  # The name of the deployment
spec:
  selector:
    matchLabels:
      app: echo  # The selector for the pods managed by this deployment
  template:
    metadata:
      labels:
        app: echo  # The label for the pods created by this deployment
    spec:
      containers:
      - name: echo  # The name of the container inside the pod
        args: ["-text=bar"]  # The arguments passed to the application/command inside the container. In this case, it will print "bar"
