name: Kind
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup kind
        run: |
          export GOBIN=$(go env GOPATH)/bin
          export PATH=$PATH:$GOBIN
          mkdir -p $GOBIN

          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x kubectl && mv kubectl $GOBIN
          wget https://github.com/kubernetes-sigs/kind/releases/download/v0.5.0/kind-linux-amd64 && chmod +x kind-linux-amd64 && mv kind-linux-amd64 $GOBIN/kind

          kind create cluster --config kind/config.yaml --wait 300s
          export KUBECONFIG="$(kind get kubeconfig-path)"

          kubectl wait --for=condition=Ready pods --all --namespace kube-system
          kubectl get nodes

      - name: Setup helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v0.44.0/k6-v0.44.0-linux-amd64.tar.gz -L | tar xvz --strip-components 1

      - name: Install foo service and test
        run: |
          npx wait-on https://google.com
          MY_URL=https://google.com ./k6 run --out csv=/tmp/foo.csv k6s/script.js

      - name: PR comment with foo test results
        uses: mshick/add-pr-comment@v2
        with:
          message-path: /tmp/foo.csv

      - name: Install bar service and test
        run: |
          npx wait-on https://google.com
          MY_URL=https://google.com ./k6 run --out csv=bar.csv k6s/script.js

      - name: PR comment with bar test results
        uses: mshick/add-pr-comment@v2
        with:
          message-path: /tmp/bar.csv
